# Generated by Django 6.0.8 on 2026-08-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('qtl', 'Quintal'), ('dozen', 'Dozen'), ('piece', 'Piece'), ('bundle', 'Bundle')], default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Grains', 'Grains'), ('Pulses', 'Pulses'), ('Spices', 'Spices'), ('Plantation', 'Plantation'), ('Fibre', 'Fibre'), ('Others', 'Others')], default='Others', max_length=50),
        ),
    ]
